_target_: modules.dataset.celeba.CelebaDataset
root: ./data/img_align_celeba
transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [64, 64]

    - _target_: torchvision.transforms.CenterCrop
      size: [64, 64]

    - _target_: torchvision.transforms.RandomHorizontalFlip

    - _target_: torchvision.transforms.ToTensor
